export const MODAL_TYPE = {
  NONE: "NONE",
  EDIT_ITEM: "EDIT_ITEM",
  CREATE_COLLECTION: "CREATE_COLLECTION",
  CREATE_COLLECTION_STEPS: "CREATE_COLLECTION_STEPS",
  MINT_TOKEN_STEPS: "MINT_TOKEN_STEPS",
};

export const STATE = {
  IDLE: "IDLE",
  BUSY: "BUSY",
  FAILED: "FAILED",
  SUCCEED: "SUCCEED",
};

export const COLLECTION_TYPE = {
  NATIVE: "NATIVE",
  USER: "USER",
  CELEB: "CELEB",
};
